name: fetch-data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * *'
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: bash ./fetch-inventory.sh
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add inventory.json
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
